import sys

from PyQt6.QtWidgets import QApplication, QHBoxLayout, QPushButton, QWidget, QLabel, QVBoxLayout, QGridLayout

app = QApplication([])
window = QWidget()
# window.setWindowTitle("PyQt App")
window.setGeometry(100, 100, 280, 80)
# pane_1 = QWidget()
# pane_2 = QWidget()
# pane_3 = QWidget()
# layout2_1 = QVBoxLayout()
# layout2_1.addWidget(QPushButton('top'))
# layout2_1.addWidget(QPushButton('middle'))
# layout2_1.addWidget(QPushButton('bottom'))
# layout2_2 = QVBoxLayout()
# layout2_2.addWidget(QPushButton('top'))
# layout2_2.addWidget(QPushButton('middle'))
# layout2_2.addWidget(QPushButton('bottom'))
# layout2_3 = QVBoxLayout()
# layout2_3.addWidget(QPushButton('top'))
# layout2_3.addWidget(QPushButton('middle'))
# layout2_3.addWidget(QPushButton('bottom'))
# pane_1.setLayout(layout2_1)
# pane_2.setLayout(layout2_2)
# pane_3.setLayout(layout2_3)
# layout1 = QHBoxLayout()
# layout1.addWidget(pane_1)
# layout1.addWidget(pane_2)
# layout1.addWidget(pane_3)
# window.setLayout(layout1)
# helloMsg = QLabel("<h1>Hello, World!</h1>", parent=window)
# helloMsg.move(60, 15)

window.setWindowTitle("QGridLayout")

layout = QGridLayout()
layout.addWidget(QPushButton("Button (0, 0)"), 0, 0)
layout.addWidget(QPushButton("Button (0, 1)"), 0, 1)
layout.addWidget(QPushButton("Button (0, 2)"), 0, 2)
layout.addWidget(QPushButton("Button (1, 0)"), 1, 0)
layout.addWidget(QPushButton("Button (1, 1)"), 1, 1)
layout.addWidget(QPushButton("Button (1, 2)"), 1, 2)
layout.addWidget(QPushButton("Button (2, 0)"), 2, 0)
layout.addWidget(
    QPushButton("Button (2, 1) + 2 Columns Span"), 2, 1, 1, 4
)
window.setLayout(layout)
window.show()
sys.exit(app.exec())
